# Generated by Django 3.0.4 on 2020-05-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0002_auto_20200511_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='podcast.Podcast'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='podcast',
            name='feed_url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
    ]
