# Generated by Django 3.0.4 on 2020-05-11 10:05

from django.db import migrations
import django.forms.widgets
from .. import models as podcast_models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0004_podcastpage_title_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock()), ('podcast', wagtail.blocks.StructBlock([('podcast', wagtail.blocks.ChooserBlock(target_model=podcast_models.Podcast, widget=django.forms.widgets.Select)), ('description', wagtail.blocks.RichTextBlock())]))], null=True),
        ),
    ]
