# Generated by Django 4.2.4 on 2023-08-14 18:11

import apps.podcast.models
from django.db import migrations, models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0010_auto_20200527_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('podcast', wagtail.blocks.StructBlock([('podcast', apps.podcast.models.PodcastChooserBlock()), ('description', wagtail.blocks.RichTextBlock())]))], null=True, use_json_field=True),
        ),
    ]
