# Generated by Django 4.2.4 on 2024-11-04 08:27

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0011_alter_episode_id_alter_podcast_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('podcast', 2)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'home/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('apps.podcast.blocks.PodcastChooserBlock', (), {'template': 'podcast/podcast_block.html'})}, null=True),
        ),
    ]
