# Generated by Django 4.2.4 on 2024-04-15 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_joinorganizationpage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinorganizationpage',
            name='city_help_text',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
