services:
  db:
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:13.5-alpine
    volumes:
    - .:/app:rw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    env_file: .env-local
    links:
    - db:postgres
    ports:
    - 8080:80
    volumes:
    - .:/app:rw
    - ./data:/data:rw
version: '2'
