services:
  database_default:
    environment:
      POSTGRES_DB: db
      POSTGRES_HOST_AUTH_METHOD: trust
      SERVICE_MANAGER: fsm-postgres
    image: postgres:13.5-alpine
    volumes:
    - .:/app:rw
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:80
    env_file:
    - path: .env-dev
      required: true
    - path: .env-local
      required: false
    links:
    - database_default
    ports:
    - 8080:80
    volumes:
    - .:/app:rw
    - ./data:/data:rw
