# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsitem_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='intro',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
