# Generated by Django 4.2.4 on 2023-08-15 04:28

from django.db import migrations, models
import django.db.models.deletion
import wagtailnews.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_snipcartsettings_site_alter_homepage_body_and_more'),
        ('news', '0006_alter_newsitem_id_alter_newsitemrevision_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsIndex',
            fields=[
                ('normalpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.normalpage')),
            ],
            bases=(wagtailnews.models.NewsIndexMixin, 'home.normalpage'),
        ),
    ]
