# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='trip_advisor',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='mewe',
            field=models.URLField(blank=True, help_text='Your MeWe page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL'),
        ),
    ]
