# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 07:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('kalikos_site', '0004_brandingsettings_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandingsettings',
            name='logo',
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='brandingsettings',
            name='header_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
