# Generated by Django 2.0.8 on 2018-12-05 07:29

from django.db import migrations

def delete_old_images(apps, schema_editor):
    Image = apps.get_model('wagtailimages', 'Image')
    Image.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0008_auto_20181204_0745'),
        ('home', '0009_image_change'),
        ('event', '0011_image_change'),
        ('news', '0005_image_change'),
        ('wagtail_publications', '0006_image_change'),
    ]

    operations = [
        migrations.RunPython(delete_old_images),
    ]
