# Generated by Django 3.0.9 on 2020-08-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    def __init__(self, name, app_label):
        super().__init__(name, app_label)
        self.app_label = 'puput'

    dependencies = [
        ('kalikos_site', '0009_delete_old_images'),
        ('puput', '0005_blogpage_main_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage', verbose_name='Header image'),
        ),
        migrations.AlterField(
            model_name='entrypage',
            name='header_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage', verbose_name='Header image'),
        ),
    ]
