# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0003_brandingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='email',
            field=models.EmailField(default='info@example.com', max_length=254),
            preserve_default=False,
        ),
    ]
