# Generated by Django 2.0.8 on 2018-12-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0007_create_kalikosimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandingsettings',
            name='footer_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
        migrations.AlterField(
            model_name='brandingsettings',
            name='header_logo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
    ]
