# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0009_delete_old_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='discord',
            field=models.URLField(blank=True, help_text='Your Discord invite URL'),
        ),
    ]
