# Generated by Django 3.2.18 on 2023-03-10 13:06

from django.db import migrations, models
import wagtail.images.models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0010_add_discord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kalikosimage',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_upload_to, verbose_name='file', width_field='width'),
        ),
        migrations.AlterField(
            model_name='kalikosimage',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='kalikosrendition',
            name='file',
            field=wagtail.images.models.WagtailImageField(height_field='height', upload_to=wagtail.images.models.get_rendition_upload_to, width_field='width'),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='discord',
            field=models.URLField(blank=True, help_text='Your Discord invite link'),
        ),
    ]
