# Generated by Django 4.2.4 on 2026-01-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0012_remove_brandingsettings_site_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalikosimage',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='description'),
        ),
    ]
