# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 15:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='datetime',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='event_name',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 15, 46, 59, 141482), verbose_name='Event end date and time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventpage',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 31, 15, 47, 13, 376568), verbose_name='Event start date and time'),
            preserve_default=False,
        ),
    ]
