# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('event', '0002_auto_20181031_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
