# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventindexpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
