# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_eventpage_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='urls',
            field=wagtail.fields.StreamField((('urls', wagtail.blocks.StructBlock((('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())))),), blank=True),
        ),
    ]
