# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('event', '0008_auto_20181108_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('paragraph', wagtail.blocks.RichTextBlock())], default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventindexpage',
            name='title_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='urls',
            field=wagtail.fields.StreamField([('urls', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())], template='event/urls_block.html'))], blank=True),
        ),
    ]
