# Generated by Django 2.0.8 on 2018-12-04 11:14

from django.db import migrations
from .. import models
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20181117_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('events', models.EventsBlock())]),
        ),
    ]
