# Generated by Django 4.2.4 on 2023-08-14 18:11

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_image_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('events', wagtail.blocks.StructBlock([('event_type', wagtail.blocks.ChoiceBlock(choices=[('get_past', 'Menneet'), ('get_upcoming', 'Tulevat')])), ('alt_text', wagtail.blocks.RichTextBlock())]))], use_json_field=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='urls',
            field=wagtail.fields.StreamField([('urls', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock()), ('url', wagtail.blocks.URLBlock())], template='event/urls_block.html'))], blank=True, use_json_field=True),
        ),
    ]
