# Generated by Django 4.2.4 on 2025-02-06 06:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0012_alter_eventindexpage_body_alter_eventpage_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('events', 4)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'home/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('get_past', 'Menneet'), ('get_upcoming', 'Tulevat')]}), 3: ('wagtail.blocks.IntegerBlock', (), {'default': 3}), 4: ('wagtail.blocks.StructBlock', [[('event_type', 2), ('alt_text', 1), ('default_amount', 3)]], {})}),
        ),
    ]
