# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-31 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20181031_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactspage',
            name='address',
            field=models.TextField(),
        ),
    ]
