# Generated by Django 4.2.4 on 2023-08-14 18:11

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_snipcartsettings_secret_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snipcartsettings',
            name='site',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('news', wagtail.blocks.StructBlock([('amount', wagtail.blocks.IntegerBlock())], template='home/blocks/news.html')), ('events', wagtail.blocks.StructBlock([('event_type', wagtail.blocks.ChoiceBlock(choices=[('get_past', 'Menneet'), ('get_upcoming', 'Tulevat')])), ('alt_text', wagtail.blocks.RichTextBlock())], template='home/blocks/events.html'))], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='normalpage',
            name='body',
            field=wagtail.fields.StreamField([('heading', wagtail.blocks.CharBlock(form_classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True, use_json_field=True),
        ),
        migrations.AlterField(
            model_name='snipcartsettings',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
