# Generated by Django 4.2.4 on 2024-05-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_snipcartsettings_site_alter_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipcartsettings',
            name='member_discount_name',
            field=models.CharField(blank=True, help_text='The name of the discount code for members', max_length=255, null=True),
        ),
    ]
