# Generated by Django 4.2.4 on 2025-02-06 06:42

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_snipcartsettings_member_discount_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 0), ('paragraph', 1), ('news', 3), ('events', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'full title', 'template': 'home/blocks/heading.html'}), 1: ('wagtail.blocks.RichTextBlock', (), {}), 2: ('wagtail.blocks.IntegerBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('amount', 2)]], {'template': 'home/blocks/news.html'}), 4: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('get_past', 'Menneet'), ('get_upcoming', 'Tulevat')]}), 5: ('wagtail.blocks.IntegerBlock', (), {'default': 3}), 6: ('wagtail.blocks.StructBlock', [[('event_type', 4), ('alt_text', 1), ('default_amount', 5)]], {'template': 'home/blocks/events.html'})}),
        ),
    ]
