# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_eventpage_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location_exact',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
