# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-08 12:00
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_eventpage_location_exact'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='urls',
            field=wagtail.fields.StreamField((('url', wagtail.blocks.URLBlock()),), blank=True),
        ),
    ]
