# Generated by Django 2.0.8 on 2018-12-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20181204_0514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventindexpage',
            name='title_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
    ]
