# Generated by Django 3.0.4 on 2020-05-11 09:38

from django.db import migrations, models
import podcast.models
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField()),
                ('number', models.CharField(max_length=10)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='podcastpage',
            name='body',
            field=wagtail.fields.StreamField([('podcast', podcast.models.PodcastBlock())], null=True),
        ),
    ]
