# Generated by Django 3.0.4 on 2020-05-11 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kalikos_site', '0009_delete_old_images'),
        ('podcast', '0003_auto_20200511_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcastpage',
            name='title_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
    ]
