# Generated by Django 3.0.6 on 2020-05-12 05:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import podcast.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0005_auto_20200511_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='url',
            new_name='link',
        ),
        migrations.AddField(
            model_name='episode',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='podcast.Podcast'),
        ),
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('podcast', wagtail.core.blocks.StructBlock([('podcast', podcast.models.PodcastChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
