# Generated by Django 3.0.6 on 2020-05-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0006_auto_20200512_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
