# Generated by Django 3.0.6 on 2020-05-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0007_episode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='image',
        ),
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
