# Generated by Django 3.0.6 on 2020-05-12 10:03

from django.db import migrations, models
import podcast.models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0008_auto_20200512_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='podcastpage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('podcast', wagtail.core.blocks.StructBlock([('podcast', podcast.models.PodcastChooserBlock()), ('description', wagtail.core.blocks.RichTextBlock())]))], null=True),
        ),
    ]
