# Generated by Django 3.0.6 on 2020-05-27 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podcast', '0009_auto_20200512_0503'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-date']},
        ),
    ]
