# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 10:06
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20181031_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='normalpage',
            name='body',
            field=wagtail.core.fields.StreamField((('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())), blank=True),
        ),
    ]
