# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 12:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_normalpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField((('heading', wagtail.blocks.CharBlock(classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()))),
        ),
        migrations.AlterField(
            model_name='normalpage',
            name='body',
            field=wagtail.fields.StreamField((('heading', wagtail.blocks.CharBlock(classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())), blank=True),
        ),
    ]
