# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-01 18:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('home', '0006_auto_20181101_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='text_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
