# Generated by Django 2.0.8 on 2018-12-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_text_image'),
        ('kalikos_site', '0007_create_kalikosimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalpage',
            name='title_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
    ]
