# Generated by Django 2.0.8 on 2018-12-04 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20181204_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='text_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kalikos_site.KalikosImage'),
        ),
    ]
