# Generated by Django 2.0.13 on 2019-06-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_image_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='title_subtext',
            field=models.TextField(default='Title subtext'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homepage',
            name='title_text',
            field=models.TextField(default='Title text'),
            preserve_default=False,
        ),
    ]
