# Generated by Django 2.0.13 on 2019-06-05 07:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190605_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(classname='full title', template='home/blocks/heading.html')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('news', wagtail.core.blocks.StructBlock([('amount', wagtail.core.blocks.IntegerBlock())], template='home/blocks/news.html')), ('events', wagtail.core.blocks.StructBlock([('event_type', wagtail.core.blocks.ChoiceBlock(choices=[('get_past', 'Menneet'), ('get_upcoming', 'Tulevat')])), ('alt_text', wagtail.core.blocks.RichTextBlock())], template='home/blocks/events.html'))], blank=True),
        ),
    ]
