# Generated by Django 3.0.6 on 2020-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_snipcartsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='snipcartsettings',
            name='secret_api_key',
            field=models.CharField(blank=True, help_text='Your Snipcart secret API key', max_length=255, null=True),
        ),
    ]
