# Generated by Django 3.2.18 on 2023-03-20 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0013_snipcartsettings_secret_api_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumSearchPage',
            fields=[
                ('normalpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.normalpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('home.normalpage',),
        ),
    ]
