# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_text_image'),
        ('wagtail_publications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationindexpage',
            name='page_ptr',
        ),
        migrations.AddField(
            model_name='publicationindexpage',
            name='normalpage_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='home.NormalPage'),
            preserve_default=False,
        ),
    ]
