# Generated by Django 3.0.6 on 2020-05-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0009_issuepage_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='pdf_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
