# Generated by Django 3.0.6 on 2020-05-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0010_issuepage_pdf_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='pdf_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='publicationpage',
            name='snipcart_digital_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
