# Generated by Django 3.2.18 on 2023-03-10 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0014_auto_20200527_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wagtail_publications.publicationpage'),
        ),
    ]
