# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-02 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0002_auto_20181102_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationpage',
            name='name',
        ),
    ]
