# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0003_remove_publicationpage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuepage',
            name='name',
        ),
        migrations.AddField(
            model_name='issuepage',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issuepage',
            name='publication_date',
            field=models.DateField(default=datetime.datetime(2018, 11, 3, 17, 25, 36, 157344, tzinfo=utc)),
        ),
    ]
