# Generated by Django 2.0.8 on 2018-12-04 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0004_auto_20181103_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='publication_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
