# Generated by Django 3.0.6 on 2020-05-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0006_image_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='sku',
            field=models.CharField(default='default', max_length=10),
            preserve_default=False,
        ),
    ]
