# Generated by Django 3.0.6 on 2020-05-13 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0007_publicationpage_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='snipcart_digital_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
