# Generated by Django 3.0.6 on 2020-05-27 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0011_auto_20200513_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuepage',
            name='weight',
            field=models.IntegerField(choices=[('lehti', 200), ('kirja', 1500)], default=200),
            preserve_default=False,
        ),
    ]
