# Generated by Django 3.0.6 on 2020-05-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0012_issuepage_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationpage',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(200, 'lehti'), (1500, 'kirja')], default=0),
        ),
        migrations.AlterField(
            model_name='issuepage',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(200, 'lehti'), (1500, 'kirja')], default=0),
        ),
    ]
