# Generated by Django 3.0.6 on 2020-05-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_publications', '0013_auto_20200527_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuepage',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(200, 'lehti'), (1500, 'kirja')], null=True),
        ),
        migrations.AlterField(
            model_name='publicationpage',
            name='weight',
            field=models.IntegerField(blank=True, choices=[(200, 'lehti'), (1500, 'kirja')], null=True),
        ),
    ]
